# Generated by Django 5.0.10 on 2025-01-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0648_remove_stream_stream_post_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="enable_guest_user_dm_warning",
            field=models.BooleanField(default=True),
        ),
    ]
